"""Add MoodCheckin model.

Revision ID: 245040e243b1
Revises: 10431942fac3
Create Date: 2025-09-17 06:51:45.824927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245040e243b1'
down_revision = '10431942fac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_hash', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['email_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_hash')

    # ### end Alembic commands ###
