"""Implement multi-step registration and confidential data model.

Revision ID: 3fcc53a3b9a4
Revises: df3ac28c38a2
Create Date: 2025-09-08 20:50:53.662047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcc53a3b9a4'
down_revision = 'df3ac28c38a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_code_email'), ['email'], unique=False)

    op.create_table('confidential_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('parent_name', sa.String(length=150), nullable=False),
    sa.Column('parent_phone_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))

    op.drop_table('confidential_data')
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_code_email'))

    op.drop_table('verification_code')
    # ### end Alembic commands ###
