"""Add MoodCheckin model.

Revision ID: 538e56151293
Revises: 245040e243b1
Create Date: 2025-09-17 23:16:45.258946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '538e56151293'
down_revision = '245040e243b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('user_message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('bot_response',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('conversation_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_column('botpress_payload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('botpress_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('conversation_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('bot_response',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_message',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
