"""Add ChatHistory model

Revision ID: 909f02e02fb0
Revises: de884b4f3258
Create Date: 2025-09-10 22:32:49.843322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909f02e02fb0'
down_revision = 'de884b4f3258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('botpress_payload', sa.JSON(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('bot_response', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_history_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_conversation_id'))

    op.drop_table('chat_history')
    # ### end Alembic commands ###
