"""Add MoodCheckin model.

Revision ID: b1344c4eec12
Revises: 9e872cb706a7
Create Date: 2025-09-16 21:24:47.618147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1344c4eec12'
down_revision = '9e872cb706a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
