"""Add MoodCheckin model.

Revision ID: d3517f08c800
Revises: 538e56151293
Create Date: 2025-09-18 11:25:03.642701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3517f08c800'
down_revision = '538e56151293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('session_ended_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('session_ended_at')
        batch_op.drop_column('session_started_at')

    # ### end Alembic commands ###
