name: Deploy Zenture Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.50.252.32
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Zenture_backend
            git fetch origin
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            pip install eventlet
            sudo sed -i 's/^ExecStart=.*/ExecStart=\/home\/ubuntu\/Zenture_backend\/venv\/bin\/gunicorn --worker-class eventlet -w 1 -b 127.0.0.1:8000 app:app/' /etc/systemd/system/zenture.service
            sudo systemctl daemon-reload
            sudo systemctl restart zenture